In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("AI_Impact_on_Jobs_2030.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Job_Title                    3000 non-null   object
 1   Average_Salary               3000 non-null   int64
 2   Years_Experience             3000 non-null   int64
 3   Education_Level              3000 non-null   object
 4   AI_Exposure_Index            3000 non-null   float64
 5   Tech_Growth_Factor           3000 non-null   float64
 6   Automation_Probability_2030  3000 non-null   float64
 7   Risk_Category                3000 non-null   object
 8   Skill_1                      3000 non-null   float64
 9   Skill_2                      3000 non-null   float64
 10  Skill_3                      3000 non-null   float64
 11  Skill_4                      3000 non-null   float64
 12  Skill_5                      3000 non-null   float64
 13  Skill_6                      3000 non-null   float64
 14  Skill_7                      3000 non-null   float64
 15  Skill_8                      3000 non-null   float64
 16  Skill_9                      3000 non-null   float64
 17  Skill_10                     3000 non-null   float64
dtypes: float64(13), int64(2), object(3)
memory usage: 422.0+ KB

In [5]:
df.head(10)

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,Skill_10
0,Security Guard,45795,28,Master's,0.18,1.28,0.85,High,0.45,0.10,0.46,0.33,0.14,0.65,0.06,0.72,0.94,0.00
1,Research Scientist,133355,20,PhD,0.62,1.11,0.05,Low,0.02,0.52,0.40,0.05,0.97,0.23,0.09,0.62,0.38,0.98
2,Construction Worker,146216,2,High School,0.86,1.18,0.81,High,0.01,0.94,0.56,0.39,0.02,0.23,0.24,0.68,0.61,0.83
3,Software Engineer,136530,13,PhD,0.39,0.68,0.60,Medium,0.43,0.21,0.57,0.03,0.84,0.45,0.40,0.93,0.73,0.33
4,Financial Analyst,70397,22,High School,0.52,1.46,0.64,Medium,0.75,0.54,0.59,0.97,0.61,0.28,0.30,0.17,0.02,0.42
5,AI Engineer,92592,11,Master's,0.29,0.51,0.10,Low,0.71,0.79,0.61,0.93,0.65,0.91,0.85,0.45,0.10,0.37
6,Mechanic,107373,23,PhD,0.67,1.09,0.41,Medium,0.56,0.38,0.97,0.85,0.72,0.24,0.26,0.04,0.71,0.11
7,Teacher,53419,12,High School,0.20,1.40,0.17,Low,0.56,0.70,0.14,0.60,0.54,0.20,0.94,0.60,0.69,0.88
8,HR Specialist,139225,12,Master's,0.30,0.61,0.48,Medium,0.22,0.42,0.88,0.32,0.12,0.36,0.91,0.27,0.65,0.00
9,Customer Support,85016,2,High School,0.01,1.01,0.80,High,0.22,0.12,0.34,0.94,0.32,0.52,0.70,0.36,0.97,0.96

# Step 2 — loc (label-based selection)

# Example 1 — Select columns by name

In [7]:
df.loc[:,["Average_Salary", "Years_Experience"]]

      Average_Salary  Years_Experience
0              45795                28
1             133355                20
2             146216                 2
3             136530                13
4              70397                22
...              ...               ...
2995          111319                 6
2996           44363                29
2997           61325                23
2998          110296                 7
2999          123909                25

[3000 rows x 2 columns]

# Example 2 — Filter rows with a condition

In [9]:
df.loc[df["Average_Salary"] == 44363, ["Average_Salary", "Years_Experience"]]

      Average_Salary  Years_Experience
2996           44363                29

# Example 3 — Single row by index label

In [10]:
df.loc[4]

Job_Title                      Financial Analyst
Average_Salary                             70397
Years_Experience                              22
Education_Level                      High School
AI_Exposure_Index                           0.52
Tech_Growth_Factor                          1.46
Automation_Probability_2030                 0.64
Risk_Category                             Medium
Skill_1                                     0.75
Skill_2                                     0.54
Skill_3                                     0.59
Skill_4                                     0.97
Skill_5                                     0.61
Skill_6                                     0.28
Skill_7                                      0.3
Skill_8                                     0.17
Skill_9                                     0.02
Skill_10                                    0.42
Name: 4, dtype: object

# Step 3 — iloc (position-based selection)

# Example 1 — First 5 rows, first 3 columns

In [13]:
df.iloc[:5, :3]

             Job_Title  Average_Salary  Years_Experience
0       Security Guard           45795                28
1   Research Scientist          133355                20
2  Construction Worker          146216                 2
3    Software Engineer          136530                13
4    Financial Analyst           70397                22

# Example 2 — Row 2, column 4

In [14]:
df.iloc[2, 4]

np.float64(0.86)

# Example 3 — First 10 rows, specific columns

In [15]:
df.iloc[:10, [0,6]]

             Job_Title  Automation_Probability_2030
0       Security Guard                         0.85
1   Research Scientist                         0.05
2  Construction Worker                         0.81
3    Software Engineer                         0.60
4    Financial Analyst                         0.64
5          AI Engineer                         0.10
6             Mechanic                         0.41
7              Teacher                         0.17
8        HR Specialist                         0.48
9     Customer Support                         0.80

# Step 5 — Missing values (NaN) — guaranteed quiz topic

# Find missing values

In [17]:
df.isna().sum()

Job_Title                      0
Average_Salary                 0
Years_Experience               0
Education_Level                0
AI_Exposure_Index              0
Tech_Growth_Factor             0
Automation_Probability_2030    0
Risk_Category                  0
Skill_1                        0
Skill_2                        0
Skill_3                        0
Skill_4                        0
Skill_5                        0
Skill_6                        0
Skill_7                        0
Skill_8                        0
Skill_9                        0
Skill_10                       0
dtype: int64

# Fill missing values (most common)

In [20]:
df["Average_Salary"] = df["Average_Salary"].fillna("Unknown")

# Drop rows with missing values (use carefully)

In [ ]:
df.dropna()

# Or only for one column:

In [21]:
df.dropna(subset=["Average_Salary"])

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,Skill_10
0,Security Guard,45795,28,Master's,0.18,1.28,0.85,High,0.45,0.10,0.46,0.33,0.14,0.65,0.06,0.72,0.94,0.00
1,Research Scientist,133355,20,PhD,0.62,1.11,0.05,Low,0.02,0.52,0.40,0.05,0.97,0.23,0.09,0.62,0.38,0.98
2,Construction Worker,146216,2,High School,0.86,1.18,0.81,High,0.01,0.94,0.56,0.39,0.02,0.23,0.24,0.68,0.61,0.83
3,Software Engineer,136530,13,PhD,0.39,0.68,0.60,Medium,0.43,0.21,0.57,0.03,0.84,0.45,0.40,0.93,0.73,0.33
4,Financial Analyst,70397,22,High School,0.52,1.46,0.64,Medium,0.75,0.54,0.59,0.97,0.61,0.28,0.30,0.17,0.02,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Doctor,111319,6,Bachelor's,0.24,1.18,0.20,Low,0.73,0.37,0.99,0.07,0.08,0.92,0.65,0.33,0.76,0.45
2996,UX Researcher,44363,29,PhD,0.65,0.74,0.35,Medium,0.23,0.48,0.05,0.88,0.56,0.29,0.69,0.80,0.61,0.20
2997,Data Scientist,61325,23,Master's,0.64,0.94,0.39,Medium,0.28,0.62,0.73,0.21,0.96,0.01,0.70,0.29,0.48,0.57
2998,Graphic Designer,110296,7,PhD,0.95,1.23,0.46,Medium,0.21,0.18,0.14,0.22,0.55,0.68,0.31,0.55,0.34,0.70
2999,Graphic Designer,123909,25,PhD,0.69,0.56,0.49,Medium,0.77,0.54,0.95,0.05,0.29,0.22,0.77,0.52,0.14,0.29

# Step 6 — Fix dirty column names (real-world data)

In [22]:
df.columns = df.columns.str.strip()